ZONES = [
    {
        "name": "Zone A, Wayanad",
        "lat": 11.6854,
        "lon": 76.1321,
        "risk_score": 87,
        "risk_level": "CRITICAL",
        "rainfall": 142,
        "soil_moisture": 78,
        "slope_deg": 31,
        "historical_incidents": 7,
        "risk_explanation": "Heavy rainfall, saturated soil, and steep slopes combine to drive this zone into a critical risk state.",
        "recommendation": "Avoid vulnerable roads and prepare evacuation measures for residential settlements.",
        "priority": "Priority 1 — Immediate attention",
        "vulnerable_locations": ["School A", "Hospital B", "Road segment 7"],
    },
    {
        "name": "Zone B, Nilgiris",
        "lat": 11.4064,
        "lon": 76.6932,
        "risk_score": 52,
        "risk_level": "MODERATE",
        "rainfall": 74,
        "soil_moisture": 62,
        "slope_deg": 26,
        "historical_incidents": 4,
        "risk_explanation": "Conditions are concerning but not yet critical. Rainfall and moisture remain elevated.",
        "recommendation": "Monitor closely and inspect vulnerable cut slopes.",
        "priority": "Priority 2 — Monitor",
        "vulnerable_locations": ["Bridge 3", "Road segment 2"],
    },
    {
        "name": "Zone C, Darjeeling",
        "lat": 27.0410,
        "lon": 88.2663,
        "risk_score": 81,
        "risk_level": "CRITICAL",
        "rainfall": 160,
        "soil_moisture": 80,
        "slope_deg": 34,
        "historical_incidents": 8,
        "risk_explanation": "Extended heavy rainfall and steep terrain produce a high likelihood of slope failure.",
        "recommendation": "High-priority inspection and evacuation alert for at-risk settlements.",
        "priority": "Priority 1 — Immediate attention",
        "vulnerable_locations": ["School D", "Road segment 8", "Hospital C"],
    },
    {
        "name": "Zone D, Kodaikanal",
        "lat": 10.2381,
        "lon": 77.4892,
        "risk_score": 33,
        "risk_level": "LOW",
        "rainfall": 48,
        "soil_moisture": 54,
        "slope_deg": 20,
        "historical_incidents": 2,
        "risk_explanation": " rain is moderate and slope is manageable. Risk remains low but should be monitored.",
        "recommendation": "Routine monitoring is sufficient unless rainfall intensifies.",
        "priority": "Priority 3 — Low priority",
        "vulnerable_locations": ["Road segment 1"],
    },
]
